name: "makeobj"
author: "G_alumi"
description: "Generate simutrans pak files with makeobj"
inputs:
  work-directory:
    description: "Directory to execute makeobj"
    default: ""
    required: false

  tilesize:
    description: "Specify tile size (128, etc.)"
    default: ""
    required: false

  dat-path:
    description: "Specify dat path"
    default: ""
    required: false

  pak-path:
    description: "Specify pak path (default is output.pak)"
    default: "output.pak"
    required: false

runs:
  using: "composite"
  steps:
    - name: "Install makeobj"
      shell: "bash"
      run: "sudo apt-get install simutrans-makeobj"

    - name: "Change directory"
      shell: "bash"
      run: "cd ${{ inputs.work-directory }}"

    - name: "Execute makeobj"
      shell: "bash"
      run: "makeobj pak${{ inputs.tilesize }} ${{ inputs.pak-path }} ${{ inputs.dat-path }}"
    
  
  